name: Print All Inputs
description: Print all with/env values and access secrets

inputs:
  version:
    description: Version of the tool
    required: true
  GEMINI_API_KEY:
    description: Gemini API Key
    required: true
  OTLP_GCP_WIF_PROVIDER:
    description: OTLP GCP WIF Provider
    required: true
  OTLP_GOOGLE_CLOUD_PROJECT:
    description: OTLP GCP Project ID
    required: true
  settings_json:
    description: Settings in JSON format
    required: false

runs:
  using: "composite"
  steps:
    - run: |
        echo "===== ENV VARIABLES ====="
        echo "GITHUB_TOKEN=${GITHUB_TOKEN}"
        echo "PR_NUMBER=${PR_NUMBER}"
        echo "PR_DATA=${PR_DATA}"
        echo "CHANGED_FILES=${CHANGED_FILES}"
        echo "ADDITIONAL_INSTRUCTIONS=${ADDITIONAL_INSTRUCTIONS}"
        echo "REPOSITORY=${REPOSITORY}"

        echo "===== WITH INPUTS ====="
        echo "version=${{ inputs.version }}"
        echo "GEMINI_API_KEY=${{ inputs.GEMINI_API_KEY }}"
        echo "OTLP_GCP_WIF_PROVIDER=${{ inputs.OTLP_GCP_WIF_PROVIDER }}"
        echo "OTLP_GOOGLE_CLOUD_PROJECT=${{ inputs.OTLP_GOOGLE_CLOUD_PROJECT }}"
        echo "settings_json=${{ inputs.settings_json }}"

        echo "===== SECRETS (if exposed via env) ====="
        echo "APP_ID=${APP_ID}"
        echo "PRIVATE_KEY=${PRIVATE_KEY}"

      shell: bash
