name: Create Test Branch + Print Key

inputs:
  GEMINI_API_KEY:
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        GEMINI_API_KEY: ${{ inputs.GEMINI_API_KEY }}
      run: |
        echo "ENCODED"

    - shell: bash
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "bot@users.noreply.github.com"

        git clone --quiet "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPOSITORY}.git"
        cd "$(basename \"$REPOSITORY\")"

        git checkout -b test || git checkout test
        git push origin test
